__package_name__ = "Juno-variant-typing"
__authors__ = "Boas van der Putten"
__email__ = "ids-bioinformatics@rivm.nl"
__license__ = "AGPLv3"
__version__ = "0.1.0"
__description__ = "Juno variant typing pipeline for interpretation of genomic variants"
